### ISSUE TITLE
Cannot find module 'unplugin-auto-import/vite'

### ISSUE THREAD

**Issue by webtj** [antfu/unplugin-auto-import#153]
help help  please!!!
```json
"devDependencies": {
    "@vitejs/plugin-vue": "^2.3.0",
    "@vue/compiler-sfc": "^3.1.2",
    "sass": "^1.50.0",
    "stylus": "^0.57.0",
    "unplugin-auto-import": "^0.7.0",
    "unplugin-vue-components": "^0.19.2",
    "vite": "^2.9.0"
  }
````
vite.config.js
```javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

import path from 'path'

const resolve = dir => {
  return path.join(__dirname, dir)
}

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
    alias: {
      '@': resolve('src'),
      '_c': resolve('src/components'),
      '_v': resolve('src/view')
    }
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: '@import "@/styles/index.scss";',
      },
    },
  },
  plugins: [
    vue(),
    AutoImport({
      resolvers: [ElementPlusResolver({
        importStyle: "sass"
      })],
    }),
    Components({
      resolvers: [ElementPlusResolver({
        importStyle: "sass"
      })],
    })
  ]
})
```

error ==>
```
Error: Cannot find module 'unplugin-auto-import/vite'
Require stack:
- E:\webStudy\Vue3.0\vite-vue3-admin\vite.config.js
- E:\webStudy\Vue3.0\vite-vue3-admin\node_modules\vite\dist\node\chunks\dep-611778e0.js
- E:\webStudy\Vue3.0\vite-vue3-admin\node_modules\vite\dist\node\cli.js
- E:\webStudy\Vue3.0\vite-vue3-admin\node_modules\vite\bin\vite.js
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (E:\webStudy\Vue3.0\vite-vue3-admin\vite.config.js:30:28)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.require.extensions.<computed> [as .js] (E:\webStudy\Vue3.0\vite-vue3-admin\node_modules\vite\dist\node\chunks\dep-611778e0.js:61506:20)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
```

**Comment by chenbingchang** [comment]
import AutoImport from 'unplugin-auto-import/dist/vite'
import Components from 'unplugin-vue-components/dist/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/dist/resolvers'

**Comment by webtj** [comment]
This problem has been solved，nodejs version is too low
thks

**Comment by webtj** [comment]
> 改成下面这样就好了。我个人觉得应该的node版本太低导致没有识别出package.json里面的 ![image](https://user-images.githubusercontent.com/43459077/165467484-f3261d30-7019-49ef-89fd-864e7a250545.png) 导致的，所以直接手动写完整路径就可以了 import AutoImport from 'unplugin-auto-import/dist/vite' import Components from 'unplugin-vue-components/dist/vite' import { ElementPlusResolver } from 'unplugin-vue-components/dist/resolvers'

thks
