### ISSUE TITLE
Nuxt type error  The 'request' argument must be string

### ISSUE THREAD

**Issue by seonglae** [antfu/unplugin-auto-import#21]
![image](https://user-images.githubusercontent.com/27716524/131605805-fce8bce5-1ae1-4c33-b6c6-95b854d5cd43.png)

I am using nuxt version 2.14.7

after added below, above error occered
```js
 buildModules: [
    '@nuxtjs/composition-api/module',
    { include: [/\.[tj]sx?$/, /\.vue\??/] }
  ]
```

Is there somethind more I have to do to use this module? I have no idea with this error

```
 FATAL  The 'request' argument must be string. Received type undefined

  at node_modules/esm/esm.js:1:224803
  at Module.<anonymous> (node_modules/esm/esm.js:1:295892)
  at Resolver.n [as _require] (node_modules/esm/esm.js:1:279589)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:615:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:180:38)
  at node_modules/@nuxt/utils/dist/utils.js:1846:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:715:5)


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │   ✖ Nuxt Fatal Error                                           │
   │                                                                │
   │   TypeError: The 'request' argument must be string. Received   │
   │   type undefined                                               │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by antfu** [comment]
Emm, do you mean?

```
 buildModules: [
    '@nuxtjs/composition-api/module',
    ['unplugin-auto-import', { include: [/\.[tj]sx?$/, /\.vue\??/] }]
 ]
```

**Comment by seonglae** [comment]
Sorry for my mistake. Thanks for kind answer
