### ISSUE TITLE
defineProps is not defined

### ISSUE THREAD

**Issue by pipinet** [antfu/unplugin-auto-import#245]
### Describe the bug

- console logs
```logs
search-bar.vue:12 Uncaught (in promise) ReferenceError: defineProps is not defined
    at setup (search-bar.vue:12:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7165:29)
    at setupComponent (runtime-core.esm-bundler.js:7120:11)
    at mountComponent (runtime-core.esm-bundler.js:5473:13)
    at processComponent (runtime-core.esm-bundler.js:5448:17)
    at patch (runtime-core.esm-bundler.js:5038:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5587:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:25)
    at instance.update (runtime-core.esm-bundler.js:5694:56)
```

- code
```vue
<script lang="ts" setup>
import { bool } from 'vue-types';
const { search } = toRefs(defineProps({
  search: bool().def(true),
}));
const emits = defineEmits<{(event: 'on-search'): void }>();
const onSearch = () => {
  emits('on-search');
};
</script>
```

### Reproduction

ignore

### System Info

```Shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 508.93 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 101.0
    Safari: 15.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by mklueh** [comment]
@antfu I'm running into the same issue. 

**defineProps** does not seem to be included in `auto-imports.d.ts` and my application is throwing 

> MyComponent.vue:21 Uncaught ReferenceError: defineProps is not defined

I'm using the vite configuration provided in the readme.

**Comment by fdietz** [comment]
Here's a hint in the Vue documentation: https://eslint.vuejs.org/user-guide/#compiler-macros-such-as-defineprops-and-defineemits-generate-no-undef-warnings

You can use [vue-eslint-parser](https://github.com/vuejs/vue-eslint-parser) v9.0.0 or need to add `vue/setup-compiler-macros` in your `.eslintrc` file in the `env` section.
