### ISSUE TITLE
Error: [auto-import] failed to load @vueuse/core, have you installed it?

### ISSUE THREAD

**Issue by catch6** [antfu/unplugin-auto-import#31]
```log
[20:19:40] failed to load config from /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/vite.config.ts
[20:19:40] error during build:
[20:19:40] Error: [auto-import] failed to load @vueuse/core, have you installed it?
[20:19:40]     at vueuse_core_default (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-T5OU4655.js:227:13)
[20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:39:51
[20:19:40]     at Array.forEach (<anonymous>)
[20:19:40]     at flattenImportsMap (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:34:36)
[20:19:40]     at resolveOptions (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:18:19)
[20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:159:20
[20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin@0.2.7@unplugin/dist/index.js:79:23
[20:19:40]     at Object.<anonymous> (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/vite.config.ts:43:28)
[20:19:40]     at Module._compile (internal/modules/cjs/loader.js:1251:30)
[20:19:40]     at Object.require.extensions.<computed> [as .ts] (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_vite@2.5.3@vite/dist/node/chunks/dep-1be34a63.js:77161:20)
[20:19:40] npm info lifecycle wenzuo-auth-fe@1.0.0~build: Failed to exec build script
[20:19:40] npm ERR! code ELIFECYCLE
[20:19:40] npm ERR! errno 1
[20:19:40] npm ERR! wenzuo-auth-fe@1.0.0 build: `vue-tsc --noEmit && vite build`
[20:19:40] npm ERR! Exit status 1
[20:19:40] npm ERR! 
[20:19:40] npm ERR! Failed at the wenzuo-auth-fe@1.0.0 build script.
[20:19:40] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[20:19:40] npm timing npm Completed in 9112ms
[20:19:40] 
[20:19:40] npm ERR! A complete log of this run can be found in:
```

this is my config
```js

  // https://github.com/antfu/unplugin-auto-import
  AutoImport({
    imports: [
      'vue',
      'vue-router',
      '@vueuse/core',
      '@vueuse/head'
    ],
    dts: true,
  }),

```

**Comment by inreasons** [comment]
> ```
> [20:19:40] failed to load config from /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/vite.config.ts
> [20:19:40] error during build:
> [20:19:40] Error: [auto-import] failed to load @vueuse/core, have you installed it?
> [20:19:40]     at vueuse_core_default (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-T5OU4655.js:227:13)
> [20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:39:51
> [20:19:40]     at Array.forEach (<anonymous>)
> [20:19:40]     at flattenImportsMap (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:34:36)
> [20:19:40]     at resolveOptions (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:18:19)
> [20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin-auto-import@0.3.3@unplugin-auto-import/dist/chunk-5I5CMYBW.js:159:20
> [20:19:40]     at /root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_unplugin@0.2.7@unplugin/dist/index.js:79:23
> [20:19:40]     at Object.<anonymous> (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/vite.config.ts:43:28)
> [20:19:40]     at Module._compile (internal/modules/cjs/loader.js:1251:30)
> [20:19:40]     at Object.require.extensions.<computed> [as .ts] (/root/workspace/wenzuo5_wenzuo-auth-fe_nfgy/node_modules/_vite@2.5.3@vite/dist/node/chunks/dep-1be34a63.js:77161:20)
> [20:19:40] npm info lifecycle wenzuo-auth-fe@1.0.0~build: Failed to exec build script
> [20:19:40] npm ERR! code ELIFECYCLE
> [20:19:40] npm ERR! errno 1
> [20:19:40] npm ERR! wenzuo-auth-fe@1.0.0 build: `vue-tsc --noEmit && vite build`
> [20:19:40] npm ERR! Exit status 1
> [20:19:40] npm ERR! 
> [20:19:40] npm ERR! Failed at the wenzuo-auth-fe@1.0.0 build script.
> [20:19:40] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [20:19:40] npm timing npm Completed in 9112ms
> [20:19:40] 
> [20:19:40] npm ERR! A complete log of this run can be found in:
> ```
> 
> this is my config
> 
> ```js
>   // https://github.com/antfu/unplugin-auto-import
>   AutoImport({
>     imports: [
>       'vue',
>       'vue-router',
>       '@vueuse/core',
>       '@vueuse/head'
>     ],
>     dts: true,
>   }),
> ```

试试在 vite.config.ts 的插件配置还有 tsconfig.json 的include字段里加一下配置？我之前用也有点报错信息，加上配置以后就好了
```js
AutoImport({
      include: [
        /\.[tj]sx?$/, // .ts, .tsx, .js, .jsx
        /\.vue\??/, // .vue
      ],
      imports: [
        'vue',
        'vue-router',
        '@vueuse/core',
        '@vueuse/head'
      ],
      dts: true
    })
```


// tsconfig.json
```json
"include": [
  "auto-imports.d.ts"
]
```

**Comment by antfu** [comment]
Should be fixed with v0.4.5

**Comment by npmrun** [comment]
when i use @vueuse/core 8.x, it also got this error

> Should be fixed with v0.4.5

**Comment by darknessitachi** [comment]
when i use @vueuse/core 8.x, it also got this error

**Comment by davidboom95** [comment]
Same here
