### ISSUE TITLE
设置cache:true

### ISSUE THREAD

**Issue by jackZmym** [antfu/unplugin-auto-import#339]
### Describe the bug

{
  "src/components/DefaultScreen/index.vue": [
    {
      "from": "@vueuse/core",
      "name": "useVModel",
      "as": "useVModel"
    },
    {
      "from": "vue",
      "name": "ref",
      "as": "ref"
    },
    {
      "from": "vue",
      "name": "reactive",
      "as": "reactive"
    },
    {
      "from": "vue",
      "name": "watch",
      "as": "watch"
    },
    {
      "from": "@vueuse/core",
      "name": "useDateFormat",
      "as": "useDateFormat"
    }
  ],
  "src/components/TabTitle/index.vue": [
    {
      "from": "vue",
      "name": "ref",
      "as": "ref"
    }
  ],
  "src/components/YqDialog/index.vue": [
    {
      "from": "@vueuse/core",
      "name": "useVModel",
      "as": "useVModel"
    }
  ],
  "src/components/SortCaret/index.vue": [
    {
      "from": "@vueuse/core",
      "name": "useVModel",
      "as": "useVModel"
    },
    {
      "from": "vue",
      "name": "computed",
      "as": "computed"
    },
    {
      "from": "vue",
      "name": "ref",
      "as": "ref"
    }
  ],
  "src/components/v-charts/useCharts.ts": [
    {
      "from": "vue",
      "name": "shallowRef",
      "as": "shallowRef"
    },
    {
      "from": "vue",
      "name": "nextTick",
      "as": "nextTick"
    },
    {
      "from": "vue",
      "name": "useAttrs",
      "as": "useAttrs"
    },
    {
      "from": "vue",
      "name": "onBeforeUnmount",
      "as": "onBeforeUnmount"
    },
    {
      "from": "vue",
      "name": "shallowReactive",
      "as": "shallowReactive"
    }
  ],
  "src/components/YqTable/index.vue": [
    {
      "from": "vue",
      "name": "ref",
      "as": "ref"
    }
  ],
  "src/hooks/useDateInterval.ts": [
    {
      "from": "vue",
      "name": "ref",
      "as": "ref"
    },
    {
      "from": "@vueuse/core",
      "name": "useIntervalFn",
      "as": "useIntervalFn"
    },
    {
      "from": "vue",
      "name": "nextTick",
      "as": "nextTick"
    }
  ]
}-plus/es/components/notification/style/css"
      ]
    }
  ]
},
      "sideEffects": [
        "element-plus/es/components/base/style/css",
        "element-plus/es/components/message-box/style/css"
      ]
    }
  ]
}

### Reproduction

cache缓存文件的json报错

### System Info

```Shell
vite] connected.
client.ts:249 [vite] Internal Server Error
Unexpected number in JSON at position 1944
    at JSON.parse (<anonymous>)
    at getCacheData (/Users/zhangsir/Desktop/舆情监测前台系统/yqm-front/node_modules/.pnpm/unplugin-auto-import@0.14.4_@vueuse+core@9.13.0/node_modules/unplugin-auto-import/dist/chunk-SSVXEZ6E.cjs:216:17)
    at async /Users/zhangsir/Desktop/舆情监测前台系统/yqm-front/node_modules/.pnpm/unplugin-auto-import@0.14.4_@vueuse+core@9.13.0/node_modules/unplugin-auto-import/dist/chunk-SSVXEZ6E.cjs:244:25
    at async Object.modifyDynamicImports (/Users/zhangsir/Desktop/舆情监测前台系统/yqm-front/node_modules/.pnpm/unimport@2.2.4/node_modules/unimport/dist/shared/unimport.03102b3e.cjs:784:20)
    at async updateCacheImports (/Users/zhangsir/Desktop/舆情监测前台系统/yqm-front/node_modules/.pnpm/unplugin-auto-import@0.14.4_@vueuse+core@9.13.0/node_modules/unplugin-auto-import/dist/chunk-SSVXEZ6E.cjs:243:5)
    at async Object.transform (/Users/zhangsir/Desktop/舆情监测前台系统/yqm-front/node_modules/.pnpm/unplugin-auto-import@0.14.4_@vueuse+core@9.13.0/node_modules/unplugin-auto-import/dist/chunk-SSVXEZ6E.cjs:267:5)
    at async Object.transform (file:///Users/zhangsir/Desktop/%E8%88%86%E6%83%85%E7%9B%91%E6%B5%8B%E5%89%8D%E5%8F%B0%E7%B3%BB%E7%BB%9F/yqm-front/node_modules/.pnpm/vite@4.1.4_4eaycc3336swc56yc3pdsd353y/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
    at async loadAndTransform (file:///Users/zhangsir/Desktop/%E8%88%86%E6%83%85%E7%9B%91%E6%B5%8B%E5%89%8D%E5%8F%B0%E7%B3%BB%E7%BB%9F/yqm-front/node_modules/.pnpm/vite@4.1.4_4eaycc3336swc56yc3pdsd353y/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackZmym** [comment]
生成的unplugin-auto-import.json不是一个正确的格式 报错
